# Generated by Django 5.0 on 2025-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('blog', 'Blog'), ('app', 'App'), ('art', 'Art'), ('workshop', 'Workshop')], default='blog', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('bodyMarkdown', models.TextField(blank=True)),
                ('coverUrl', models.URLField(blank=True)),
                ('publishedAt', models.DateTimeField(auto_now_add=True)),
                ('isPublished', models.BooleanField(default=True)),
                ('metaJson', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-publishedAt'],
            },
        ),
    ]
